export const INSTRUCTOR_REGISTER = "INSTRUCTOR_REGISTER";
export const ADMIN_ENTERED = "ADMIN_ENTERED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
